name: omnesoft_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  auto_route: ^11.0.0
  cached_network_image: ^3.4.1
  faker: ^2.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_inset_shadow: ^2.0.3
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  rxdart: ^0.28.0
  shared_preferences: ^2.5.4
  sqflite: ^2.4.2
  table_calendar: ^3.2.0

dev_dependencies:
  auto_route_generator: ^10.4.0
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
